# Form implementation generated from reading ui file 'C:\Users\igorx\PycharmProjects\Yandex_Project\.venv\edit_card.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(530, 606)
        Form.setStyleSheet("QWidget {\n"
"    color:white\n"
"}\n"
"QWidget#Form {\n"
"    background-color: red;\n"
"};\n"
"")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(90, 60, 361, 461))
        self.frame.setStyleSheet("QFrame#frame {\n"
"    background-color:  #14141c;\n"
"    border: 2px solid rgba(255,255,255,0.3);\n"
"    border-radius : 16px solid;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #14141c;\n"
"    font-size: 18px;\n"
"    color: #898c95;\n"
"    border-radius: 8px;\n"
"    border: 1.5px solid rgba(255,255,255,0.3);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(96, 74, 237);\n"
"}\n"
"\n"
"QPlainTextEdit#plainTextEdit {\n"
"    background-color: #14141c;\n"
"    font-size: 18px;\n"
"    color: #898c95;\n"
"    border-radius: 8px;\n"
"    border: 2px solid rgba(255,255,255,0.3);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(96, 74, 237);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(30, 20, 311, 51))
        self.label.setStyleSheet("font-size:25px;")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(30, 90, 301, 41))
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.frame)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 150, 301, 41))
        self.lineEdit_3.setStyleSheet("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(parent=self.frame)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 200, 301, 71))
        self.plainTextEdit.setStyleSheet("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.label.raise_()
        self.lineEdit.raise_()
        self.frame.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.frame.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\">ывпы</p></body></html>"))
        self.label.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("Form", "Редактирование задачи"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Название задачи"))
        self.lineEdit_3.setPlaceholderText(_translate("Form", "Описание задачи"))
        self.plainTextEdit.setPlaceholderText(_translate("Form", "Описание задачи"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
