# Form implementation generated from reading ui file 'C:\Users\Игорь\PycharmProjects\Yandex_Project\edit_card.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(618, 767)
        Form.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        Form.setStyleSheet("QWidget {\n"
"    color:white\n"
"}\n"
"QWidget#Form {\n"
"    background-color: #12121a;\n"
"};\n"
"")
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setGeometry(QtCore.QRect(90, 60, 441, 541))
        self.frame.setStyleSheet("QFrame#frame {\n"
"    background-color:  #14141c;\n"
"    border: 1px solid rgba(255,255,255,0.3);\n"
"    border-radius : 16px solid;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: #14141c;\n"
"    font-size: 18px;\n"
"    color: #898c95;\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgba(255,255,255,0.3);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(96, 74, 237);\n"
"    outline: 2px solid rgba(127,90,240, 0.20)\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    width: 15px;\n"
"    height:15px;\n"
"    border:1px solid black;\n"
"    border-radius: 8px;\n"
"    background: white;\n"
"}\n"
"QRadioButton::indicator:checked{\n"
"    background: orange;\n"
"    border: 1px solid #666666;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(30, 20, 311, 51))
        self.label.setStyleSheet("font-size:25px;")
        self.label.setObjectName("label")
        self.nameEdit = QtWidgets.QLineEdit(parent=self.frame)
        self.nameEdit.setGeometry(QtCore.QRect(30, 90, 381, 41))
        self.nameEdit.setStyleSheet("")
        self.nameEdit.setText("")
        self.nameEdit.setObjectName("nameEdit")
        self.discriptionEdit = QtWidgets.QPlainTextEdit(parent=self.frame)
        self.discriptionEdit.setGeometry(QtCore.QRect(30, 150, 381, 81))
        self.discriptionEdit.setStyleSheet("QPlainTextEdit{\n"
"background-color: #14141c;\n"
"font-size: 18px;\n"
"color: #898c95;\n"
"border-radius: 10px;\n"
"border: 1px solid rgba(255,255,255,0.3);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(96, 74, 237);\n"
"    outline: 2px solid rgba(127,90,240, 0.20)\n"
"}")
        self.discriptionEdit.setObjectName("discriptionEdit")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 320, 191, 50))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Priority = QtWidgets.QLabel(parent=self.layoutWidget)
        self.Priority.setStyleSheet("color: #898c95;\n"
"font-size: 18px;")
        self.Priority.setObjectName("Priority")
        self.verticalLayout.addWidget(self.Priority)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.priorButton_1 = QtWidgets.QRadioButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(24)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.priorButton_1.sizePolicy().hasHeightForWidth())
        self.priorButton_1.setSizePolicy(sizePolicy)
        self.priorButton_1.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.priorButton_1.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.priorButton_1.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.priorButton_1.setStyleSheet("")
        self.priorButton_1.setText("")
        self.priorButton_1.setObjectName("priorButton_1")
        self.buttonGroup = QtWidgets.QButtonGroup(Form)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.setExclusive(False)
        self.buttonGroup.addButton(self.priorButton_1)
        self.horizontalLayout_2.addWidget(self.priorButton_1)
        self.priorButton_2 = QtWidgets.QRadioButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(24)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.priorButton_2.sizePolicy().hasHeightForWidth())
        self.priorButton_2.setSizePolicy(sizePolicy)
        self.priorButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.priorButton_2.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.priorButton_2.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.priorButton_2.setStyleSheet("")
        self.priorButton_2.setText("")
        self.priorButton_2.setObjectName("priorButton_2")
        self.buttonGroup.addButton(self.priorButton_2)
        self.horizontalLayout_2.addWidget(self.priorButton_2)
        self.priorButton_3 = QtWidgets.QRadioButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(24)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.priorButton_3.sizePolicy().hasHeightForWidth())
        self.priorButton_3.setSizePolicy(sizePolicy)
        self.priorButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.priorButton_3.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.priorButton_3.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.priorButton_3.setStyleSheet("")
        self.priorButton_3.setText("")
        self.priorButton_3.setObjectName("priorButton_3")
        self.buttonGroup.addButton(self.priorButton_3)
        self.horizontalLayout_2.addWidget(self.priorButton_3)
        self.priorButton_4 = QtWidgets.QRadioButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(24)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.priorButton_4.sizePolicy().hasHeightForWidth())
        self.priorButton_4.setSizePolicy(sizePolicy)
        self.priorButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.priorButton_4.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.priorButton_4.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.priorButton_4.setStyleSheet("")
        self.priorButton_4.setText("")
        self.priorButton_4.setObjectName("priorButton_4")
        self.buttonGroup.addButton(self.priorButton_4)
        self.horizontalLayout_2.addWidget(self.priorButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(24)
        sizePolicy.setVerticalStretch(24)
        sizePolicy.setHeightForWidth(self.radioButton_5.sizePolicy().hasHeightForWidth())
        self.radioButton_5.setSizePolicy(sizePolicy)
        self.radioButton_5.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.radioButton_5.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.radioButton_5.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.PreventContextMenu)
        self.radioButton_5.setStyleSheet("")
        self.radioButton_5.setText("")
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup.addButton(self.radioButton_5)
        self.horizontalLayout_2.addWidget(self.radioButton_5)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 240, 381, 70))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.date_label = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.date_label.setStyleSheet("color: #898c95;\n"
"font-size: 18px;")
        self.date_label.setObjectName("date_label")
        self.verticalLayout_2.addWidget(self.date_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.layoutWidget1)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setStyleSheet("background-color: #14141c;")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\Игорь\\PycharmProjects\\Yandex_Project\\icons/dark_theme/calendar-event-line.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(28, 28))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.layoutWidget1)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.layoutWidget2 = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget2.setGeometry(QtCore.QRect(30, 380, 201, 57))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget2)
        self.label_2.setStyleSheet("color: #898c95;\n"
"font-size: 18px;")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(parent=self.layoutWidget2)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    background-color: #12121a;\n"
"    font-size: 18px;\n"
"    color: #898c95;\n"
"    border-radius: 8px;\n"
"    border: 1px solid rgba(255,255,255,0.3);\n"
"}\n"
"\n"
"QComboBox QAbstarctItemView {\n"
"    background: black;\n"
"}\n"
"QComboBox:on {\n"
"    border: 2px solid rgb(96, 74, 237);\n"
"    outline: 2px solid rgba(127,90,240, 0.20);\n"
"    background-color: #12121a;\n"
"}\n"
"\n"
"\n"
"QComboBox:focus {\n"
"    border: 2px solid rgb(96, 74, 237);\n"
"    outline: 2px solid rgba(127,90,240, 0.20)\n"
"}")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.verticalLayout_3.addWidget(self.comboBox)
        self.layoutWidget3 = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget3.setGeometry(QtCore.QRect(80, 470, 291, 41))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setStyleSheet("background: rgb(96, 74, 237);\n"
"border-radius:16px;\n"
"border: 1px solid rgba(255,255,255,0.3);\n"
"font-size: 20px;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(Form)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.pushButton_2)
        self.horizontalLayout_3.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.layoutWidget3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_3.setStyleSheet("border: 1px solid rgba(255,255,255,0.3);\n"
"border-radius : 16px ;\n"
"font-size: 20px;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.buttonGroup_2.addButton(self.pushButton_3)
        self.horizontalLayout_3.addWidget(self.pushButton_3)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.frame.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\">ывпы</p></body></html>"))
        self.label.setWhatsThis(_translate("Form", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.label.setText(_translate("Form", "Редактирование задачи"))
        self.nameEdit.setPlaceholderText(_translate("Form", "Название задачи"))
        self.discriptionEdit.setPlaceholderText(_translate("Form", "Описание задачи"))
        self.Priority.setText(_translate("Form", "Приоритет"))
        self.date_label.setText(_translate("Form", "Дата"))
        self.label_2.setText(_translate("Form", "Уровень сложности"))
        self.comboBox.setItemText(0, _translate("Form", "Easy"))
        self.comboBox.setItemText(1, _translate("Form", "Normal"))
        self.comboBox.setItemText(2, _translate("Form", "Hard"))
        self.pushButton_2.setText(_translate("Form", "Измеить"))
        self.pushButton_3.setText(_translate("Form", "Отмена"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
